spring:
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SecurityDemo
    username: Hamza
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql-server
    database-platform: org.hibernate.dialect.SQLServerDialect